package com.anahuac.rest.api.DB

class StatementsCatalogos {
	
	//CatEjemplo
	public static final String INSERT_CATTIPOMONEDA = "INSERT INTO CATTIPOMONEDA (PERSISTENCEID, CLAVE, DESCRIPCION, FECHACREACION, ISELIMINADO, PERSISTENCEVERSION, USUARIOCREACION) VALUES ((SELECT CASE WHEN max(PERSISTENCEID) IS NULL THEN 1 ELSE max(PERSISTENCEID)+1 END FROM CATTIPOMONEDA), ?, ?, now(), false, 1, ?);";

	public static final String INSERTCATFILTROSEGURIDAD = "INSERT INTO PSGRFILTROSEGURIDAD (PERSISTENCEID, PERSISTENCEVERSION, ROL, SERVICIO) VALUES ((SELECT COALESCE(MAX(PERSISTENCEID), 0) + 1 FROM PSGRFILTROSEGURIDAD), ?, ?, ?)";
	public static final String DELETECATFILTROSEGURIDAD = "DELETE FROM PSGRFILTROSEGURIDAD WHERE PERSISTENCEID = ?";
	public static final String UPDATECATFILTROSEGURIDAD = "UPDATE PSGRFILTROSEGURIDAD SET ROL = ?, SERVICIO = ? WHERE PERSISTENCEID = ?";
}
